---
- name: Download EPEL
  become: no
  get_url:
    url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    dest: /usr/local/src/epel.rpm

- name: Install EPEL
  become: no
  yum:
    name: /usr/local/src/epel.rpm
    state: present

- name: Install Certbot
  become: no
  yum:
    name: python2-certbot-apache.noarch
    state: present

- name: Create webroot directory where files for ACME challenge will be stored
  become: no
  file: path={{ certbot_webroot }} state=directory recurse=yes

- name: Add nginx virtualhost for ACME challenge
  become: yes
  template:
    src: "templates/certbot.nginx.conf.j2"
    dest: "/etc/nginx/conf.d/certbot.nginx.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: Restarting nginx
  become: no
  meta: flush_handlers

- name: Obtain certificates with webroot plugin
  become: yes
  command: "certbot certonly --noninteractive --webroot --webroot-path {{ certbot_webroot }} {% for domain in certbot_domains %}-d {{ domain }} {% endfor %} --agree-tos --email {{ certbot_email }}"

- name: Update links from nginx to certificates
  become: no
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
    force: yes
  with_items:
    - { src: '/etc/letsencrypt/live/{{ domain }}/privkey.pem', dest: '/etc/nginx/ssl/{{ domain }}/privkey.pem' }
    - { src: '/etc/letsencrypt/live/{{ domain }}/fullchain.pem', dest: '/etc/nginx/ssl/{{ domain }}/fullchain.pem' }
  notify: restart nginx

- name: Add cron job for certificate renewal
  become: no
  cron:
    name: Certbot automatic renewal.
    job: "certbot renew --quiet --no-self-upgrade {{ certbot_renewal_command_args }}"
    minute: "{{ certbot_auto_renew_minute }}"
    hour: "{{ certbot_auto_renew_hour }}"
    user: "{{ certbot_auto_renew_user }}"
  when: certbot_auto_renew
